version: '3.4'

services:
  scheduleworm:
    image: scheduleworm
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      API_PORT: 3000
      API_SECRET_KEY: 'secret'
    ports:
      - 3000:3000
